[package]
name = "branch-dashboard"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration"]

[dependencies]
migration = { path = "migration" } # depends on your needs

axum = "0.6.10"
axum-server = { version = "0.4.6", features = ["tokio-rustls"] }
axum-macros = "0.3.5"
anyhow = "1.0.69"
chrono = "0.4.23"
log = "0.4.17"
log4rs = "1.2.0"
reqwest = { version = "0.11.14", features = ["json", "rustls-tls"], default-features = false }
sea-orm = { version = "0.11.0", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.93"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["filter"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
config = { version = "0.13.3", features = ["json", "json5", "serde_json"], default-features = false }
