[package]
name = "gitlab-branch-dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.6"
axum-server = "0.4.0"
anyhow = "1.0.57"
chrono = "0.4.19"
log = "0.4.17"
log4rs = "1.1.1"
reqwest = { version = "0.11.10", features = ["json"] }
serde = "1.0.137"
serde_derive = "1.0.137"
serde_json = "1.0.81"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.12", features = ["filter"] }
tower-http = { version = "0.3.3", features = ["fs", "trace"] }