[package]
name = "branch-dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.17"
axum-server = "0.4.2"
anyhow = "1.0.66"
chrono = "0.4.22"
log = "0.4.17"
log4rs = "1.2.0"
reqwest = { version = "0.11.12", features = ["json"] }
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["filter"] }
tower-http = { version = "0.3.4", features = ["fs", "trace"] }
config = {version = "0.13.2", features = ["json", "json5", "serde_json"], default-features = false }
