[package]
name = "branch-dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.1"
axum-server = "0.4.4"
anyhow = "1.0.66"
chrono = "0.4.23"
log = "0.4.17"
log4rs = "1.2.0"
reqwest = { version = "0.11.13", features = ["json"] }
serde = "1.0.148"
serde_derive = "1.0.148"
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["filter"] }
tower-http = { version = "0.3.5", features = ["fs", "trace"] }
config = {version = "0.13.3", features = ["json", "json5", "serde_json"], default-features = false }
