[package]
name = "gitlab-branch-dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.1"
axum-server = "0.3.3"
anyhow = "1.0.56"
chrono = "0.4.19"
log = "0.4.16"
log4rs = "1.0.0"
reqwest = { version = "0.11.10", features = ["json"] }
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.12", features = ["filter"] }
tower-http = { version = "0.2.5", features = ["fs", "trace"] }