[package]
name = "gitlab-branch-dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.13"
axum-server = "0.4.2"
anyhow = "1.0.60"
chrono = "0.4.20"
log = "0.4.17"
log4rs = "1.1.1"
reqwest = { version = "0.11.11", features = ["json"] }
serde = "1.0.142"
serde_derive = "1.0.142"
serde_json = "1.0.83"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["filter"] }
tower-http = { version = "0.3.4", features = ["fs", "trace"] }